[package]
name = "agc"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
echonote-data = { workspace = true }
hound = { workspace = true }
rodio = { workspace = true }

[dependencies]
echonote-audio-utils = { workspace = true }
echonote-vad-ext = { workspace = true }

dagc = "0.1.1"
