[package]
name = "llm-interface"
version = "0.1.0"
edition = "2024"

[dependencies]
echonote-llama = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
